---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint:
  name: yamllint

platforms:
  - name: instance-1
    config_options:
      synced_folder: false
    box: centos/7
    memory: 512
    cpus: 1

provisioner:
  name: ansible
  options:
    become: true
  log: true
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
