---

- name: Enable SELinux
  selinux:
    policy: targeted
    state: enforcing

- name: Apply kernel parameters
  sysctl:
    state: present
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: true
  with_dict: "{{ sysctl_entries }}"