---

- name: Install EPEL repositories
  yum:
    state: present
    name: epel-release
    update_cache: true

- name: Install base packages
  yum:
    state: present
    name: "{{ base_packages[ ansible_distribution | lower ] }}"
    update_cache: true
